### ISSUE TITLE
Possible to get a terraform 0.12 / aws provider 3.x compatible version?

### ISSUE THREAD

**Issue by mwarkentin** [trussworks/terraform-aws-logs#102]
Is it possible to get a TF 0.12 version released which supports aws provider 3.x?

I think this would basically just be removing the `region` value like was done in https://github.com/trussworks/terraform-aws-logs/releases/tag/v10.0.0.

I'd be happy to open a PR if this would be welcome.

**Comment by eeeady** [comment]
Sure thing!

**Comment by eeeady** [comment]
https://github.com/trussworks/terraform-aws-logs/pull/103 <-

**Comment by eeeady** [comment]
https://github.com/trussworks/terraform-aws-logs/releases/tag/v8.3.0 🎉

**Comment by mwarkentin** [comment]
Thanks @eeeady !
