### ISSUE TITLE
Tag 8.4.0 requires tf13?

### ISSUE THREAD

**Issue by msusta** [trussworks/terraform-aws-logs#130]
In the project description there's a statement that the terraform v12 users should pin to module v8, however the latest tagged release is specifying tf13 as requirement in versions.tf?
Is there some reason for it or was that just oversight during backporting?

**Comment by msusta** [comment]
Diff for history of versions file:
https://github.com/trussworks/terraform-aws-logs/commits/v8.3.0/versions.tf
https://github.com/trussworks/terraform-aws-logs/commits/v8.4.0/versions.tf

Obviously the best thing would be to upgrade TF version, however I'm not sure how quickly I can do that for the project and I just wanted to add few modules from here.

**Comment by msusta** [comment]
So digging into Git log seems to point to rather simple problem - while 8.3.0 == terraform12 branch, PR #120 added a tag for 8.4.0 on the master branch...

**Comment by dynamike** [comment]
Yeah, it was mistakenly released off of master instead of the terraform12 branch. I think I fixed this in the 0.8.5 release. Let me know if it doesn't work.

**Comment by dynamike** [comment]
Any update on this?

**Comment by msusta** [comment]
Thanks for the quick solution! I have only validated the solution by code review - I have already migrated the code to TF13 instead.
