### ISSUE TITLE
Can we allow for a customer cmk key to be set as the encryption key?

### ISSUE THREAD

**Issue by SteveKrzysiak** [trussworks/terraform-aws-logs#151]
From main.tf I believe we'd have to adjust that section.  
```
  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
```

Would this codebase be receptive to a PR to handle either default or CMK encryption?

**Comment by eeeady** [comment]
For sure. We'd be open to a PR that could handle those cases!
