### ISSUE TITLE
Need an upgrade guide between 1.7.1 and 2.1.0

### ISSUE THREAD

**Issue by chrisgilmerproj** [trussworks/terraform-aws-logs#18]
There are a number of things that changed between the 1.7.1 and 2.1.0 release of this module.  A migration guide would be very helpful and should include a couple things:

- CloudTrail management disappeared between versions.  [Previously it was managed](https://github.com/trussworks/terraform-aws-logs/blob/v1.7.1/main.tf#L92-L176) but users now need to provide their own implementation.
- Template Provider 1.0.0 used to work with the module and now you need Template Provider 2.X or better
- Several of the resources names were changed, which means you need to use `terraform mv` to manage the transition in your own state.
- The bucket policy was [moved out of the aws_s3_bucket resource](https://github.com/trussworks/terraform-aws-logs/blob/v1.7.1/main.tf#L67) and into a [aws_s3_bucket_policy](https://github.com/trussworks/terraform-aws-logs/blob/v2.1.0/main.tf#L109-L114). While this is potentially a no-op it has the effect of making it look like your policy is being removed completely unless you specify `default_allow=true` as a variable. And then you've got to compare your new and old policy to make sure it has what you want in it.
- It adds a `aws_s3_bucket_public_access_block` with sane defaults but there's no way to change the behavior if you didn't have these set before.

A transition guide would be really helpful for folks using this module to help them move forward.  If I have time I'll try to make one but I want the issue open here to remind me.

**Comment by sojeri** [comment]
@chrisgilmerproj wondering if this should be an upgrade guide from `1.7.1` to `2.1.0` based on the policy syntax issues most consumers seemed to have (#12)

**Comment by chrisgilmerproj** [comment]
I've created a new module to manage the CloudTrail stuff that was removed in #11 . You can find it here: https://registry.terraform.io/modules/trussworks/cloudtrail/aws/1.0.0

**Comment by chrisgilmerproj** [comment]
So I think the transition plan is, if previously you had:

```hcl
locals {
  aws_logs_bucket = "my-company-aws-logs"
  log_retention_days = 731 # 2 years
  region = "us-west-2"
}

module "logs" {
  source  = "trussworks/logs/aws"
  version = "~> 1.7.1"

  enable_cloudtrail              = true
  s3_log_bucket_retention        = "${local.log_retention_days}"
  cloudwatch_log_group_retention = "${local.log_retention_days}"
  region                         = "${local.region}"
  s3_bucket_name                 = "${local.aws_logs_bucket}"
}
```

Now you'd want to have this:

```hcl
locals {
  aws_logs_bucket = "my-companyp-aws-logs"
  log_retention_days = 731 # 2 years
  region = "us-west-2"
}

module "logs" {
  source  = "trussworks/logs/aws"
  version = "~> 2.1.0"

  default_allow = true

  s3_log_bucket_retention = "${local.log_retention_days}"
  region                  = "${local.region}"
  s3_bucket_name          = "${local.aws_logs_bucket}"
}

module "aws_cloudtrail" {
  source  = "trussworks/cloudtrail/aws"
  version = "1.0.1"

  s3_bucket_name = "${local.aws_logs_bucket}"
  log_retention_days = "${local.log_retention_days}"
}
```

**Comment by chrisgilmerproj** [comment]
The move commands are these:

```
terraform state mv module.logs.aws_cloudtrail.cloudtrail module.aws_cloudtrail.aws_cloudtrail.main
terraform state mv module.logs.aws_cloudwatch_log_group.main module.aws_cloudtrail.aws_cloudwatch_log_group.cloudtrail
terraform state mv module.logs.aws_iam_policy.main module.aws_cloudtrail.aws_iam_policy.cloudtrail_cloudwatch_logs
terraform state mv module.logs.aws_iam_policy_attachment.main module.aws_cloudtrail.aws_iam_policy_attachment.main
terraform state mv module.logs.aws_iam_role.main module.aws_cloudtrail.aws_iam_role.cloudtrail_cloudwatch_role
```

**Comment by dynamike** [comment]
Moving to Pivotal -- https://github.com/trussworks/terraform-aws-logs/pull/32
