### ISSUE TITLE
`enable_versioning` for S3 buckets should also support `mfa_delete` option

### ISSUE THREAD

**Issue by nikolay** [trussworks/terraform-aws-logs#208]
If you're passing AWS FTR, `mfa_delete` is required for CloudTrail buckets.

**Comment by dynamike** [comment]
We tend to enforce this type of functionality by leaning on [AWS Organization SCPs](https://github.com/trussworks/terraform-aws-ou-scp) to prevent object deletions in buckets like cloudtrail. I could see this being valuable if you aren't using AWS Orgs. Would you mind submitting a PR with the changes? If not we can try to pick this up in the coming weeks.

**Comment by nikolay** [comment]
Yes, I am pushing the PR in a couple of hours. This is from their [AWS FTR](https://aws.amazon.com/partners/foundational-technical-review/) checklist:

> 5.d. Protect CloudTrail logs from accidental deletion or overwrite (i.e. enable MFA Delete or versioning on the Amazon Simple Storage Service (Amazon S3) bucket that stores the logs or an equivalent solution).

**Comment by nikolay** [comment]
This is the `mfa_delete` [attribute](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#mfa_delete), which needs to be exposed as a variable.

**Comment by nikolay** [comment]
@dynamike Any chance to look into the PR?
