### ISSUE TITLE
Error creating bucket. AccessControlListNotSupported: The bucket does not allow ACLs.

### ISSUE THREAD

**Issue by sunl48-roche** [trussworks/terraform-aws-logs#307]
**Describe the bug**

**To Reproduce**
1. Clone https://github.com/trussworks/terraform-aws-logs
2. cd to terraform-aws-logs/examples/s3
3. terraform apply

**Expected behavior**
Able to create bucket successfully.

**Screenshots**
n/a

**Code Snippet**
```
 ❯ terraform apply
var.force_destroy
  Enter a value: 1

var.region
  Enter a value: us-east-2

var.s3_logs_prefix
  Enter a value: pref

var.test_name
  Enter a value: tf-aws-logs-test-bucket


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

```
```
module.aws_logs.aws_s3_bucket_lifecycle_configuration.aws_logs: Creation complete after 32s [id=tf-aws-logs-test-bucket]

Error: error creating S3 bucket ACL for tf-aws-logs-test-bucket-source: AccessControlListNotSupported: The bucket does not allow ACLs
	status code: 400, request id: 6X4TZRP5EQ2YPDQ3, host id: 9mHxqkGpu11rF2zIiAn99oeV3SMHQG+zMjmnl7CK1eG6f9nQBtF7MgrAsXfpwYWCZwGRp9bBD7k=

  on main.tf line 15, in resource "aws_s3_bucket_acl" "log_source_bucket":
  15: resource "aws_s3_bucket_acl" "log_source_bucket" {



Error: error creating S3 bucket ACL for tf-aws-logs-test-bucket: AccessControlListNotSupported: The bucket does not allow ACLs
	status code: 400, request id: 3G4V9C00DNN2ZCAT, host id: OPOKoxFPHI+fhxMTT3M2kh25bWr7gOH02pY7Fp4aMjoHbdTh9Ud1+RAh1V7hvi6CIvsigoVVlX8=

  on ../../main.tf line 424, in resource "aws_s3_bucket_acl" "aws_logs":
 424: resource "aws_s3_bucket_acl" "aws_logs" {
```

**Additional context**
Possibly related to https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

**Comment by amontalban** [comment]
I'm having the exact same issue, in another bucket I'm using with https://github.com/terraform-aws-modules/terraform-aws-s3-bucket module I had to set this two variables to fix this error:

```
  control_object_ownership = true
  object_ownership         = "ObjectWriter"
```

Looks like this module is missing this resource:

```
resource "aws_s3_bucket_ownership_controls" "this" {
  count = local.create_bucket && var.control_object_ownership ? 1 : 0

  bucket = local.attach_policy ? aws_s3_bucket_policy.this[0].id : aws_s3_bucket.this[0].id

  rule {
    object_ownership = var.object_ownership
  }

  # This `depends_on` is to prevent "A conflicting conditional operation is currently in progress against this resource."
  depends_on = [
    aws_s3_bucket_policy.this,
    aws_s3_bucket_public_access_block.this,
    aws_s3_bucket.this
  ]
}
```

As a workaround I had to follow the steps described [here](https://stackoverflow.com/a/70603995), but that is not ideal.

**Comment by thebigcosinus** [comment]
Hi, I've got the same issue, I stuck my deployment to you have a new release date or a workaround ?
Thanks

**Comment by jsclarridge** [comment]
https://github.com/trussworks/terraform-aws-logs/releases/tag/v15.0.0 has been released, which should fix this. Please test and let us know if you encounter any issues with the new version.

**Comment by rpdelaney** [comment]
@revathi-bgsw Please refer to the [Upgrade paths](https://github.com/trussworks/terraform-aws-logs#upgrade-paths) docs when upgrading an existing bucket to use version 15 of this module.

By the way, check [this](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) out for help on making fenced code blocks in comments. It's easier to read than screenshots :)
