### ISSUE TITLE
request s3_bucket_name random genrator feature

### ISSUE THREAD

**Issue by mahmoudshirivaramini** [trussworks/terraform-aws-logs#47]
Add an input to the module to enable s3_bucket_name random generator, which creates  s3_bucket_name using a prefix through a variable and a [random id](https://www.terraform.io/docs/providers/random/r/id.html). For example:

s3_bucket_name = "${var.perfix}-${random_id.bucket_id.dec}"

**Comment by dynamike** [comment]
Can you talk a little bit more about why this use case would be helpful for you. On the surface it seems like just padding the randomized string into the module directly do just fine.

**Comment by mahmoudshirivaramini** [comment]
As bucket names must be unique across all existing bucket names in Amazon S3 and sometimes on infrastructure, more than a hundred buckets required, and I care about project name for buckets naming and `${var.project_name}-${random_id.bucket_id.dec}` format is desired for all of the buckets naming through the project.

**Comment by dynamike** [comment]
Thanks for the response. To me, it's important that the name exemplify the buckets function and enforcing a random string in the name moves away from that idea. So I don't think we will be implementing this functionality now.
