### ISSUE TITLE
Migrate policy JSON template to an aws_iam_policy_document data source

### ISSUE THREAD

**Issue by brainsik** [trussworks/terraform-aws-logs#7]
This is an old module and as such, uses a JSON template for the policy. Instead, it should be defined in the Terraform itself via an "aws_iam_policy_document" data source. It's far more readable that way.

**Comment by sojeri** [comment]
@brainsik should I open this in pivotal?

**Comment by brainsik** [comment]
Nope! Looks like we're now using a bunch of features of the templating language in order to handle some crazy logic. So, I'll close this out. Thanks for asking.
